name: clang-tidy

on:
  push: {}
  pull_request: {}

jobs:
  job:
    name: run-clang-tidy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3

    - name: install clang-tidy
      run: sudo apt update && sudo apt -y install clang-tidy

    - uses: bazelbuild/setup-bazelisk@v2

    - name: Install cras deps
      run: |
        sudo apt-get install -y \
          build-essential \
          ladspa-sdk \
          libasound-dev \
          libdbus-1-dev \
          libgmock-dev \
          libgtest-dev \
          libsbc-dev \
          libspeexdsp-dev \
          libudev-dev \
          python3

    - name: Build
      run: bazel run //:compdb --config=local-clang

    - name: run
      shell: bash
      run: run-clang-tidy
